version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: mymodus
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mymodus_db
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://mymodus:example@db:5432/mymodus_db
      JWT_SECRET: replace_in_production
    depends_on:
      - db
    ports:
      - "8080:8080"
volumes:
  db_data:
