version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: mymodus
      POSTGRES_PASSWORD: mymodus_pass
      POSTGRES_DB: mymodus_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    environment:
      DATABASE_URL: postgres://mymodus:mymodus_pass@db:5432/mymodus_db
      PORT: "8080"
      JWT_SECRET: "change_this_in_production"
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
