version: '3.8'
services:
  bot_service:
    build:
      context: .
      dockerfile: bot_service/Dockerfile
    environment:
      - BOT_DB=/data/bot.db
      - PLAYWRIGHT_INSTALL=false
    volumes:
      - ./bot_service:/app
      - bot_data:/data
    ports:
      - "8001:8001"
    restart: unless-stopped

volumes:
  bot_data:
