name: mymodus_backend
description: MyModus backend (shelf)
version: 0.1.0
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.0
  shelf_web_socket: ^1.0.0
  postgres: ^2.4.0
  dart_jsonwebtoken: ^2.0.1
  dotenv: ^5.0.0
  http: ^1.1.0
  path: ^1.8.0
  crypto: ^3.0.0
  uuid: ^3.0.0
  json_annotation: ^4.8.0
  botasaurus: ^1.0.0
  selenium: ^3.1.0
  webdriver: ^3.0.0
  html: ^0.15.0
  collection: ^1.17.0

dev_dependencies:
  test: ^1.21.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  lints: ^2.0.0
