name: mymodus_backend
description: MyModus backend (shelf) with Web3, AI, and marketplace parsing integration
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # Web Framework
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  shelf_cors_headers: ^0.1.5
  
  # Database
  postgres: ^2.6.3
  redis: ^3.1.0
  
  # Authentication & Security
  dart_jsonwebtoken: ^2.0.1
  crypto: ^3.0.3
  uuid: ^4.2.1
  
  # Environment & Config
  dotenv: ^4.2.0
  
  # HTTP & Parsing
  http: ^1.1.0
  html: ^0.15.4
  
  # Web3 & Blockchain
  web3dart: ^2.7.2
  bip39: ^1.0.6
  ed25519_hd_key: ^2.2.0
  
  # AI & ML
  openai_dart: ^0.3.0
  
  # File Storage & IPFS
  path: ^1.8.3
  mime: ^1.0.4
  
  # Utilities
  collection: ^1.17.2
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  
  # Testing
  test: ^1.24.9

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^2.1.1
