name: mymodus_backend
description: MyModus backend (shelf)
version: 0.1.0
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  postgres: ^2.4.0
  dart_jsonwebtoken: ^2.0.1
  dotenv: ^5.0.0
dev_dependencies:
  test: ^1.21.0
